name: Create Release
on:
  push:
    tags:
      - "*.**"

jobs:
  build_and_push:
    name: Build and push container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set env
        id: env
        shell: bash
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Log in to Docker Hub Container registry
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/ahjulstad/archimate-ci-image:${{ steps.env.outputs.tag }}
            ghcr.io/ahjulstad/archimate-ci-image:latest

          # docker.io/ahjulstad/archimate-ci-image:${{ steps.env.outputs.tag }}
          # docker.io/ahjulstad/archimate-ci-image:latest

      - name: Build and push rootless container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.rootless
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/ahjulstad/archimate-ci-image:${{ steps.env.outputs.tag }}-rootless
            ghcr.io/ahjulstad/archimate-ci-image:latest-rootless
          
          # docker.io/ahjulstad/archimate-ci-image:${{ steps.env.outputs.tag }}-rootless
          # docker.io/ahjulstad/archimate-ci-image:latest-rootless
          build-args: |
            ARCHIMATE_CI_VERSION=${{ steps.env.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            GitHub Action [Deploy Archi Report ${{ steps.env.outputs.tag }}](https://github.com/marketplace/actions/deploy-archi-report?version=${{ steps.env.outputs.tag }})

            Container images:

            ahjulstad/archimate-ci-image:**${{ steps.env.outputs.tag }}**

            * `docker pull ghcr.io/ahjulstad/archimate-ci-image:${{ steps.env.outputs.tag }}`
            * `docker pull docker.io/ahjulstad/archimate-ci-image:${{ steps.env.outputs.tag }}`

            ahjulstad/archimate-ci-image:**${{ steps.env.outputs.tag }}-rootless**

            * `docker pull ghcr.io/ahjulstad/archimate-ci-image:${{ steps.env.outputs.tag }}-rootless`
            * `docker pull docker.io/ahjulstad/archimate-ci-image:${{ steps.env.outputs.tag }}-rootless`

            > [Changelog](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md)

          draft: false
          prerelease: false
